// src/utils/data.js

// Markalar
export const brands = [
    {
        id: 'endospheres',
        name: 'Endospheres',
        logo: '/images/endospheres-logo.png',
        description: 'Profesyonel estetik ve selülit tedavi cihazları.',
        website: 'https://www.endospheres.com/en/professional-aesthetic-cellulite-treatment-machines/',
    },
    {
        id: 'dermalux',
        name: 'Dermalux LED',
        logo: '/images/dermalux-logo.png',
        description: 'LED teknolojisiyle cilt tedavisi sağlayan cihazlar.',
        website: 'https://dermaluxled.com/devices/',
    },
    {
        id: 'supernova',
        name: 'Supernova Laboratories',
        logo: '/images/supernova-logo.png',
        description: 'Peeling ve cilt yenileyici ürünler sunan bir marka.',
        website: 'https://supernovalaboratories.com/en/nebula-acto2/',
    },
    {
        id: 'aenaon',
        name: 'Aenaon',
        logo: '/images/aenaon-logo.png',
        description: 'Gelişmiş cilt bakım ürünleri.',
        website: 'https://www.aenaon.com/collections/all',
    },
    {
        id: 'caromed',
        name: 'Caromed Italia',
        logo: '/images/caromed-logo.png',
        description: 'Anti-aging ürünleri ve özel serumlar.',
        website: 'https://caromeditalia.com/products/anti-aging/',
    },
    {
        id: 'alsavique-transdermal',
        name: 'Alsavique Transdermal',
        logo: '/images/alsavique-logo.png',
        description: 'Mezoterapi ve topikal cilt uygulamaları.',
        website: '/alsavique-link',
    },
    {
        id: 'lovecosmedical',
        name: 'Love Cosmedical',
        logo: '/images/lovecosmedical-logo.png',
        description: 'Cilt yenileyici ve estetik ürünler sunan bir marka.',
        website: 'https://www.lovecosmedical.com/products-line/faceline/33-neofound-exo',
    },
];

// Ürünler
export const products = [
    {
        id: 'akbody',
        name: 'AKBODY',
        brand: 'Endospheres',
        category: 'cihazlar',
        description: 'AKBODY, selülit tedavi cihazı.',
        image: '/images/akbody.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'aksensor',
        name: 'AKSENSOR',
        brand: 'Endospheres',
        category: 'cihazlar',
        description: 'AKSENSOR, estetik tedaviler için gelişmiş bir cihazdır.',
        image: '/images/aksensor.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'flex-md',
        name: 'FLEX MD',
        brand: 'Dermalux LED',
        category: 'cihazlar',
        description: 'LED teknolojisi ile güzellik tedavisi cihazı.',
        image: '/images/flex-md.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'triwave-md',
        name: 'TRIWAVE MD',
        brand: 'Dermalux LED',
        category: 'tıbbi cihazlar',
        description: 'Tıbbi kullanım için LED cihaz.',
        image: '/images/triwave-md.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'nebula-acto2',
        name: 'NEBULA ACTO2',
        brand: 'Supernova Laboratories',
        category: 'tıbbi cihazlar',
        description: 'Peeling cihazı ile cilt tedavisi sağlar.',
        image: '/images/nebula-acto2.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'aenaon-gece-kremi',
        name: 'Aenaon Gece Kremi',
        brand: 'Aenaon',
        category: 'kozmetik',
        description: 'Cilt mükemmelleştirici gece kremi.',
        image: '/images/aenaon-gece-kremi.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'eugenie-intim-peeling',
        name: 'Eugenie İntim Peeling',
        brand: 'Caromed Italia',
        category: 'kozmetik',
        description: 'Özel bölge için anti-aging peeling ürünü.',
        image: '/images/eugenie-intim-peeling.png',
        price: 'Ürün fiyat bilgisi yok',
    },
    {
        id: 'neofound-exo',
        name: 'Neofound Exo',
        brand: 'Love Cosmedical',
        category: 'kozmetik',
        description: 'Cilt yenileyici serum.',
        image: '/images/neofound-exo.png',
        price: 'Ürün fiyat bilgisi yok',
    },
];
